pool:
  name: Default
  vmImage: ubuntu-latest

trigger:
  - develop
steps: 
- task: DotNetCoreCLI@2 
  inputs:
   command: 'build'
   projects: src/NopCommerce.sln

- task: CopyFiles@2
  inputs:
    Contents: 'src/Presentation/Nop.Web/bin/Debug/net7.0'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ecommerce-application'
    publishLocation: 'Container' 