pool:
  name: Default
  vmImage: ubuntu-latest
trigger:
  - devops

steps:  - 
- task: DotNetCoreCLI@2
  inputs:
   command: 'build'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ecommerce-application'
      publishLocation: 'Container'